# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
version=v2-alpha
mod_release_type=alpha
mod_id=sculk-radio
maven_group=nl.gjorgdy
archives_base_name=SculkRadio

# Dependencies https://modmuss50.me/fabric.html
minecraft_versions=26.2
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.154.2+26.2
fzzy_config_version=0.7.6+26.2
dev_auth_version=1.1.0

# AudioPlayer compat
admiral_version=0.4.10+26.2+fabric
audioplayer_api_version=2.4.0
audioplayer_mod_version=fabric-2.4.0+26.2
voicechat_api_version=2.6.0
voicechat_mod_version=2.6.21+26.2