# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_versions=26.1.2
minecraft_version=26.1.2
loader_version=0.19.1
loom_version=1.16-SNAPSHOT
# Fabric API
fabric_api_version=0.145.4+26.1.2
# Mod Properties
version=0.4.0
mod_release_type=beta
mod_id=sculk-radio
maven_group=nl.gjorgdy
archives_base_name=SculkRadio
# AudioPlayer compat
admiral_version=0.4.10+26.1+fabric
audioplayer_api_version=2.0.0
audioplayer_mod_version=fabric-2.2.0+26.1.2
voicechat_api_version=2.6.0
voicechat_mod_version=2.6.16+26.1.2
# Optional Config mod
fzzy_config_version=0.7.6+26.1